blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

blogs/urls.py
"""Defines URL patterns for blogs."""

from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that show all posts
    path('posts/', views.posts, name='posts'),
    # Detail page for a single post
#    path('posts/<int:post_id>/', views.post, name='post'),
    # Page for adding a new posts
    path('new_post/', views.new_post, name='new_post'),
    # Page for editing an post.
    path('edit_post/<int:post_id>', views.edit_post, name='edit_post'),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

class BlogPost(models.Model):
    """Posted information"""
    title = models.CharField(max_length=200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        """Return a string representation of the model."""
        self.title_text = self.title + ": " + self.text
        return self.title_text
        

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms

from .models import BlogPost

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        labels = {'title': '', 'text': ''}

blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import BlogPost
from .forms import BlogPostForm

def index(request):
    """The home page for Blog."""
    return render(request, 'blogs/index.html')
    
def posts(request):
    """Show all posts"""
    posts = BlogPost.objects.order_by('date_added')
    context = {'posts': posts}
    return render(request, 'blogs/posts.html', context)
"""
def post(request, post_id):
    Show single post and its text
    post = BlogPost.objects.get(id=post_id)
    context = {'post': post}
    return render(request, 'blogs/post.html', context)
"""
@login_required
def new_post(request):
    """Add a new post."""    
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = BlogPostForm
    else:
        # POST data submitted; process data.
        form = BlogPostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
            return redirect('blogs:posts')
            
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'blogs/new_post.html', context)

@login_required
def edit_post(request, post_id):
    """Edit posts."""
    post = BlogPost.objects.get(id=post_id)
    check_post_owner(request, post.owner)
    
    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = BlogPostForm(instance=post)
    else:
        # POST data submitted; process data.
        form = BlogPostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:posts')
            
    context = {'post': post, 'form': form}
    return render(request, 'blogs/edit_post.html', context)

def check_post_owner(request, owner):
    """Check post owner."""
    if owner != request.user:
        raise Http404

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.http import Http404

def register(request):
    """Register a new user."""
    if request.user.is_authenticated:
        raise Http404
    else:
        if request.method != 'POST':
            # Display blank registration form.
            form = UserCreationForm()
        else:
            # Process completed form.
            form = UserCreationForm(data=request.POST)
            
            if form.is_valid():
                new_user = form.save()
                # Log the user in and then redirect to home page.
                login(request, new_user)
                return redirect('blogs:index')
                
        # Display a blank or invalid form.
        context = {'form': form}
        return render(request, 'registration/register.html', context)
                
    

blogs/templates/blogs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
  <title>Blog</title>
  
  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}

</head>
<body>
    
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

    <a class="navbar-brand" href="{% url 'blogs:index'%}">
        Blog</a>
        
    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blogs:posts'%}">
              Posts</a></li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text">Live long and prosper, {{ user.username }}.</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
        {% endif %}
      </ul>
    </div>
    
  </nav>
  
  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>

</html>

blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<h2> Edit post</h2>  
{% endblock page_header %}

{% block content %}
  <form method="post" action="{% url 'blogs:edit_post' post.id %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="sumbit" class="btn btn-primary">Save changes</button>
    {% endbuttons %}
  </form>
{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block page_header %}
  <div class="jumbotron">
    <v1 class="display-3">Post your thoughts.</v1>
    
    <p class="lead">Write down whatever you want</p>
    {% if user.is_authenticated %}        
      <a class="btn btn-lg btn-primary" href="{% url 'blogs:posts' %}"
          role="button">Posts &raquo;</a>
    {% else %}
      <a class="btn btn-lg btn-primary" href="{% url 'users:login' %}"
          role="button">Log in &raquo;</a>
      <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
          role="button">Register &raquo;</a>
    {% endif %}
  </div>
{% endblock page_header %}

blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h2>Add a new post:</h2>
{% endblock page_header %}
{% block content %}
  <form method="post" action="{% url 'blogs:new_post' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Add post</button>
    {% endbuttons %}
  </form>

{% endblock content %}

blogs/templates/blogs/post.html
{% extends "blogs/base.html" %}

{% block content %}

  <p>Post</p>
  
  <ul>
      <li>
          <p>{{ post }}</p>
      </li>
  </ul>
  
{% endblock content %}

blogs/templates/blogs/posts.html
{% extends "blogs/base.html" %}

{% block page_header %}
  <p><h3>Posts</h3></p>
{% endblock page_header %}

{% block content %}
  <h3><a href="{% url 'blogs:new_post' %}">Add a new post</a></h3>
  
  <ul>
    {% for post in posts %}
      <li><h5>
        <b>{{ post.owner }}:</b>
        <h3>{{ post.title }}</h3>
        {{ post }}
        {% if post.owner == request.user %}
        <p>
          <a href="{% url 'blogs:edit_post' post.id %}">Edit Post</a>
        </p>
        {% endif %}
      </h5></li>
    {% empty %}
      <li><h3>No posts have been added yet.</h3></li>
    {% endfor %}
  </ul>

{% endblock content %}